require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
    - 'db/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'Rakefile'
    - 'bin/**/*'
    - lib/tasks/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/models/**/*'

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
