default: &default
  adapter: postgresql
  host: localhost
  username: ~
  password: ~

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
